const PDFJS_URL="https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs", PDFJS_WORKER_URL="https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs", ZIP_URL="https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm";
const OUTPUT=document.body.dataset.output||"jpg",IS_PNG=OUTPUT==="png",MIME=IS_PNG?"image/png":"image/jpeg",TOOL_CODE=IS_PNG?"p2p":"p2j",OUTPUT_LABEL=OUTPUT.toUpperCase();
const $=id=>document.getElementById(id), drop=$("p2jDrop"), input=$("p2jInput"), choose=$("p2jChoose"), work=$("p2jWork"), grid=$("p2jGrid"), nameEl=$("p2jName"), meta=$("p2jMeta"), quality=$("p2jQuality"), convert=$("p2jConvert"), status=$("p2jStatus"), all=$("p2jAll"), none=$("p2jNone"), replace=$("p2jReplace"), clear=$("p2jClear");
let pdf=null,_file=null,selected=new Set(),results=[];
const pick=()=>input.click(); choose.onclick=e=>{e.stopPropagation();pick()}; replace.onclick=pick; clear.onclick=reset; drop.onclick=pick; drop.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();pick()}};
["dragenter","dragover"].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add("is-dragging")})); ["dragleave","drop"].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove("is-dragging")}));
drop.ondrop=e=>load(e.dataTransfer.files[0]); input.onchange=()=>{load(input.files[0]);input.value=""}; all.onclick=()=>{selected=new Set(Array.from({length:pdf.numPages},(_,i)=>i+1));sync()}; none.onclick=()=>{selected.clear();sync()}; convert.onclick=convertPages;
async function load(f){if(!f)return;if(f.type!=="application/pdf"&&!f.name.toLowerCase().endsWith(".pdf")){msg("Only PDF files are supported.","error");return}if(f.size>100*1024*1024){msg("The PDF must be smaller than 100 MB.","error");return}try{msg("Creating page previews...","");const p=await import(/* @vite-ignore */PDFJS_URL);p.GlobalWorkerOptions.workerSrc=PDFJS_WORKER_URL;_file=f;pdf=await p.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;selected=new Set(Array.from({length:pdf.numPages},(_,i)=>i+1));nameEl.textContent=f.name;meta.textContent=`${pdf.numPages} pages · ${bytes(f.size)}`;work.hidden=false;work.classList.add("is-active");drop.hidden=true;document.body.classList.add("split-has-file");await render();sync();msg("Select the pages you want to convert.","success")}catch(e){console.error(e);msg("This PDF is damaged, encrypted or unsupported.","error")}}
async function render(){grid.innerHTML="";for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),v0=page.getViewport({scale:1}),v=page.getViewport({scale:Math.min(1.2,190/v0.width)}),b=document.createElement("button");b.type="button";b.className="split-page-card is-selected";b.dataset.page=n;b.innerHTML=`<span class="split-page-check">✓</span><canvas></canvas><strong>Page ${n}</strong>`;const c=b.querySelector("canvas");c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await page.render({canvasContext:c.getContext("2d"),viewport:v}).promise;b.onclick=()=>{if(selected.has(n))selected.delete(n);else selected.add(n);sync()};grid.appendChild(b)}}
function sync(){grid.querySelectorAll(".split-page-card").forEach(b=>b.classList.toggle("is-selected",selected.has(+b.dataset.page)));convert.disabled=!selected.size;convert.textContent=`Convert ${selected.size||0} Page${selected.size===1?"":"s"} to ${OUTPUT_LABEL}`}
async function convertPages(){convert.disabled=true;results=[];try{let i=0;for(const n of [...selected].sort((a,b)=>a-b)){msg(`Converting page ${++i} of ${selected.size}...`,"");const page=await pdf.getPage(n),v=page.getViewport({scale:2}),c=document.createElement("canvas");c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await page.render({canvasContext:c.getContext("2d"),viewport:v}).promise;const blob=await new Promise(r=>c.toBlob(r,MIME,IS_PNG?undefined:+quality.value));results.push({n,blob})}if(results.length===1)download(results[0].blob,filename(results[0].n));else{const{default:JSZip}=await import(/* @vite-ignore */ZIP_URL),zip=new JSZip();results.forEach(x=>zip.file(filename(x.n),x.blob));download(await zip.generateAsync({type:"blob"}),`creatornew-${TOOL_CODE}-pages.zip`)}msg(`${results.length} ${OUTPUT_LABEL} file${results.length===1?"":"s"} ready and downloaded.`,"success")}catch(e){console.error(e);msg("Unable to convert this PDF. Try again.","error")}finally{sync()}}
function filename(n){return`creatornew-${TOOL_CODE}-page-${String(n).padStart(3,"0")}.${OUTPUT}`}function download(blob,n){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=n;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function reset(){pdf=_file=null;selected.clear();results=[];grid.innerHTML="";work.hidden=true;work.classList.remove("is-active");drop.hidden=false;document.body.classList.remove("split-has-file");msg("","")}function msg(t,c){status.textContent=t;status.className="status"+(c?` ${c}`:"")}function bytes(n){return n>1048576?(n/1048576).toFixed(1)+" MB":(n/1024).toFixed(1)+" KB"}reset();
