import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  base: './',
  plugins: [react()],
  build: {
    assetsDir: 'creatornew-assets',
    rollupOptions: {
      input: {
        home: 'index.html',
        imageConverter: 'image-converter/index.html',
        pngToWebp: 'png-to-webp/index.html',
        jpgToWebp: 'jpg-to-webp/index.html',
        webpToJpg: 'webp-to-jpg/index.html',
        imageCompressor: 'image-compressor/index.html',
        imageResize: 'image-resize/index.html',
        backgroundRemover: 'background-remover/index.html',
        imagesToPdf: 'images-to-pdf/index.html',
        mergePdf: 'merge-pdf/index.html',
        splitPdf: 'split-pdf/index.html',
        pdfToJpg: 'pdf-to-jpg/index.html',
        rotatePdf: 'rotate-pdf/index.html',
        audioSearch: 'audio-search/index.html',
        videoSearch: 'video-search/index.html',
        freeSounds: 'free-sounds/index.html',
        freeVideos: 'free-videos/index.html',
        pdfToPng: 'pdf-to-png/index.html',
        deletePdfPages: 'delete-pdf-pages/index.html',
        aiPromptBuilder: 'ai-prompt-builder/index.html',
        imageConversionGuide: 'how-to-convert-images-online-free/index.html',
        about: 'about/index.html',
        privacyPolicy: 'privacy-policy/index.html',
        terms: 'terms/index.html',
        creatornewVsRemoveBg: 'creatornew-vs-remove-bg/index.html',
        creatornewVsTinyPng: 'creatornew-vs-tinypng/index.html',
        creatornewVsIlovePdf: 'creatornew-vs-ilovepdf/index.html',
        creatornewVsSmallpdf: 'creatornew-vs-smallpdf/index.html',
        creatornewVsEzgif: 'creatornew-vs-ezgif/index.html',
        creatornewVsConvertio: 'creatornew-vs-convertio/index.html',
        webpVsPngVsJpg: 'webp-vs-png-vs-jpg/index.html',
        howToMergePdfSecurely: 'how-to-merge-pdf-files-securely/index.html',
        creatornewVsCanva: 'creatornew-vs-canva/index.html',
        creatornewVsEpidemicSound: 'creatornew-vs-epidemic-sound/index.html',
        howToCompressImagesGuide: 'how-to-compress-images-without-losing-quality/index.html',
        socialMediaImageSizesGuide: 'social-media-image-sizes-guide-2026/index.html',
        creatornewVsAdobeAcrobat: 'creatornew-vs-adobe-acrobat/index.html',
        viHome: 'vi/index.html',
        viNenAnhDuoi200kb: 'vi/nen-anh-duoi-200kb/index.html',
        viBackgroundRemover: 'vi/background-remover/index.html',
        viImageCompressor: 'vi/image-compressor/index.html',
        viMergePdf: 'vi/merge-pdf/index.html',
        viSplitPdf: 'vi/split-pdf/index.html',
        viImageConverter: 'vi/image-converter/index.html',
        viImageResize: 'vi/image-resize/index.html',
        viPngToWebp: 'vi/png-to-webp/index.html',
        viJpgToWebp: 'vi/jpg-to-webp/index.html',
        notFound: '404.html',
      },
    },
  },
})
